# Generated by Django 5.0 on 2025-08-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uncle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Relation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='aunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('d', models.ManyToManyField(default='bibash', to='kerosene.uncle')),
            ],
        ),
    ]
